apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: argocd-proj-1
  region: us-east-1

managedNodeGroups:
  - name: argocd-proj-1-nodes
    instanceType: m5.large
    desiredCapacity: 3
    spot: true

 

