apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: spoke1-cluster
  region: us-east-1

managedNodeGroups:
  - name: spoke1-nodes
    instanceType: m5.large
    desiredCapacity: 2
    spot: true